spring:
  application:
    name: gateway
  jackson:
    default-property-inclusion: non_null
grpc:
  client:
    order-service:
      address: static://beverage-service:9090
      negotiationType: plaintext